name: CI linux-amd64

on:
  pull_request:
    types:
      - opened

jobs:
  builds:
    runs-on: [ ubuntu-20.04 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup compiler
        uses: actions/setup-go@v3
        with:
          go-version: '^1.19.6'
      - name: Test
        run: |
          make test