name: CI

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
  push:
    branches:
      - 'main'
      - 'dev-*'

jobs:
  build-test:
    strategy:
      matrix:
        platform: [macos-14, macos-13, ubuntu-20.04, windows]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install MingW64
        if: matrix.platform == 'windows'
        uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          install: >-
            mingw-w64-x86_64-gcc
      - name: Setup go compiler
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          check-latest: false
          cache: false
      - name: Test
        run: go run mage.go test
