name: CI

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
  push:
    branches:
      - 'main'
      - 'dev-*'

jobs:
  build-test:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - macos-15
          - macos-14
          - macos-13
          - ubuntu-22.04
          - ubuntu-22.04-arm
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - windows-2022
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install MINGW64
        if: startsWith(matrix.platform, 'windows')
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: >-
            mingw-w64-x86_64-gcc
      - name: Setup go compiler
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          check-latest: true
          cache: true
      - name: Test
        run: go run mage.go test
        env:
          MSYSTEM: MINGW64
