name: CI

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
  push:
    branches:
      - 'main'

jobs:
  darwin-amd64:
    runs-on: [ macos-12 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup compiler
        uses: actions/setup-go@v3
        with:
          go-version: '^1.20.7'
      - name: Test
        run: go run mage.go test
  linux-amd64:
    runs-on: [ ubuntu-20.04 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup compiler
        uses: actions/setup-go@v3
        with:
          go-version: '^1.20.7'
      - name: Test
        run: go run mage.go test